In [22]:
import numpy as np

In [23]:
def interchange(matrix, first_row_index, second_row_index):
    temp_array = np.array(matrix[first_row_index])
    matrix[first_row_index] = matrix[second_row_index]
    matrix[second_row_index] = temp_array

In [24]:
def scale(matrix, row_index, scalar):
    for i in range(matrix[row_index].size):
        matrix[row_index][i] *= scalar
        if matrix[row_index][i] == -0.:
            matrix[row_index][i] = 0.

In [25]:
def replace(matrix, first_row_index, second_row_index, scalar):
    for i in range(matrix[first_row_index].size):
        matrix[first_row_index][i] = matrix[second_row_index][i] * scalar + matrix[first_row_index][i]
        if matrix[first_row_index][i] == -0.:
            matrix[first_row_index][i] = 0.

In [26]:
pivot_dimensions = []

In [27]:
def find_pivot(matrix, uppest_pivotless_row_index):
    last_pivot_column = 0
    if len(pivot_dimensions):
        last_pivot_column = pivot_dimensions[-1][1] + 1

    for i in range(last_pivot_column, np.shape(matrix)[1] - 1):
        for j in range(uppest_pivotless_row_index, np.shape(matrix)[0]):
            if matrix[j][i] == 0:
                continue
            else:
                interchange(matrix, uppest_pivotless_row_index, j)
                pivot_dimensions.append([uppest_pivotless_row_index, i])
                return True

    return False

In [28]:
def subtract_scaled_pivot_row_from_rows_below(matrix, pivot_row, pivot_column):
    for i in range(pivot_row + 1, np.shape(matrix)[0]):
        if matrix[i][pivot_column]:
            replace(matrix, i, pivot_row, -matrix[i][pivot_column])

In [29]:
def divide_rows_by_their_pivot_entries(matrix):
    scale(matrix, pivot_dimensions[-1][0], 1 / float((matrix[pivot_dimensions[-1][0]][pivot_dimensions[-1][1]])))

In [30]:
# Forward Phase of Row Reduction algorithm
def upper_triangle_form(matrix):
    uppest_pivotless_row_index = 0
    for i in range(np.shape(matrix)[0]):
        if find_pivot(matrix, uppest_pivotless_row_index):
            divide_rows_by_their_pivot_entries(matrix)
            subtract_scaled_pivot_row_from_rows_below(matrix, pivot_dimensions[-1][0], pivot_dimensions[-1][1])
            uppest_pivotless_row_index += 1
        else:
            break

In [31]:
def subtract_scaled_pivot_row_from_rows_above(matrix, pivot_row, pivot_column):
    for i in range(pivot_row):
        if matrix[i][pivot_column]:
            replace(matrix, i, pivot_row, -matrix[i][pivot_column])

In [32]:
# Backward Phase of Row Reduction algorithm
def backward_phase(matrix):
    for i in range(np.shape(pivot_dimensions)[0]):
        subtract_scaled_pivot_row_from_rows_above(matrix, pivot_dimensions[-(i + 1)][0], pivot_dimensions[-(i + 1)][1])

In [33]:
def reduced_echelon_form(augmented_matrix):
    upper_triangle_form(augmented_matrix)
    backward_phase(augmented_matrix)
    print(augmented_matrix)

In [34]:
input_matrix = np.array([
    [1, 1, 0, 0, 0, 800],
    [0, 1, -1, 1, 0, 300],
    [0, 0, 0, 1, 1, 500],
    [1, 0, 0, 0, 1, 600]
            ],
            dtype=np.float32)

In [35]:
reduced_echelon_form(input_matrix)

[[  1.   0.   0.   0.   1. 600.]
 [  0.   1.   0.   0.  -1. 200.]
 [  0.   0.   1.   0.   0. 400.]
 [  0.   0.   0.   1.   1. 500.]]
